/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "scramble.docs.index": [],
    "scramble.docs.api": [],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "api": [],
    "apipermissions.index": [],
    "apipermissions.store": [],
    "apipermissions.show": [
        {
            "name": "permission"
        }
    ],
    "apipermissions.update": [
        {
            "name": "permission"
        }
    ],
    "apipermissions.destroy": [
        {
            "name": "permission"
        }
    ],
    "apicompanies.index": [],
    "apicompanies.store": [],
    "apicompanies.show": [
        {
            "name": "company",
            "binding": "id"
        }
    ],
    "apicompanies.update": [
        {
            "name": "company",
            "binding": "id"
        }
    ],
    "apicompanies.destroy": [
        {
            "name": "company",
            "binding": "id"
        }
    ],
    "apiinvite.index": [],
    "apiinvite.store": [],
    "apiinvite.show": [
        {
            "name": "invite"
        }
    ],
    "apiinvite.update": [
        {
            "name": "invite"
        }
    ],
    "apiinvite.destroy": [
        {
            "name": "invite",
            "binding": "id"
        }
    ],
    "apireactions.index": [],
    "apireactions.store": [],
    "apireactions.show": [
        {
            "name": "reaction"
        }
    ],
    "apireactions.update": [
        {
            "name": "reaction"
        }
    ],
    "apireactions.destroy": [
        {
            "name": "reaction"
        }
    ],
    "apichats.index": [],
    "apichats.store": [],
    "apichats.show": [
        {
            "name": "chat",
            "binding": "id"
        }
    ],
    "apichats.update": [
        {
            "name": "chat",
            "binding": "id"
        }
    ],
    "apichats.destroy": [
        {
            "name": "chat",
            "binding": "id"
        }
    ],
    "apiprojects.index": [],
    "apiprojects.store": [],
    "apiprojects.show": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "apiprojects.update": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "apiprojects.destroy": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "apitask-types.index": [],
    "apitask-types.store": [],
    "apitask-types.show": [
        {
            "name": "task_type"
        }
    ],
    "apitask-types.update": [
        {
            "name": "task_type"
        }
    ],
    "apitask-types.destroy": [
        {
            "name": "task_type"
        }
    ],
    "apirelations.index": [],
    "apirelations.store": [],
    "apirelations.show": [
        {
            "name": "relation"
        }
    ],
    "apirelations.update": [
        {
            "name": "relation"
        }
    ],
    "apirelations.destroy": [
        {
            "name": "relation"
        }
    ],
    "apitasks.index": [],
    "apitasks.store": [],
    "apitasks.show": [
        {
            "name": "task"
        }
    ],
    "apitasks.update": [
        {
            "name": "task"
        }
    ],
    "apitasks.destroy": [
        {
            "name": "task",
            "binding": "id"
        }
    ],
    "apitasks-statuses.index": [],
    "apitasks-statuses.store": [],
    "apitasks-statuses.show": [
        {
            "name": "tasks_status"
        }
    ],
    "apitasks-statuses.update": [
        {
            "name": "tasks_status",
            "binding": "id"
        }
    ],
    "apitasks-statuses.destroy": [
        {
            "name": "tasks_status"
        }
    ],
    "apiboards.index": [],
    "apiboards.store": [],
    "apiboards.show": [
        {
            "name": "board",
            "binding": "id"
        }
    ],
    "apiboards.update": [
        {
            "name": "board",
            "binding": "id"
        }
    ],
    "apiboards.destroy": [
        {
            "name": "board",
            "binding": "id"
        }
    ],
    "apisprints.index": [],
    "apisprints.store": [],
    "apisprints.show": [
        {
            "name": "sprint",
            "binding": "id"
        }
    ],
    "apisprints.update": [
        {
            "name": "sprint",
            "binding": "id"
        }
    ],
    "apisprints.destroy": [
        {
            "name": "sprint",
            "binding": "id"
        }
    ],
    "apifiles.index": [],
    "apifiles.store": [],
    "apifiles.show": [
        {
            "name": "file"
        }
    ],
    "apifiles.update": [
        {
            "name": "file"
        }
    ],
    "apifiles.destroy": [
        {
            "name": "file",
            "binding": "id"
        }
    ],
    "apiroles.index": [],
    "apiroles.store": [],
    "apiroles.show": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "apiroles.update": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "apiroles.destroy": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "apitime-sheet.index": [],
    "apitime-sheet.store": [],
    "apitime-sheet.show": [
        {
            "name": "time_sheet"
        }
    ],
    "apitime-sheet.update": [
        {
            "name": "time_sheet"
        }
    ],
    "apitime-sheet.destroy": [
        {
            "name": "time_sheet"
        }
    ],
    "apiusers.index": [],
    "apiusers.store": [],
    "apiusers.show": [
        {
            "name": "user"
        }
    ],
    "apiusers.update": [
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "apiusers.destroy": [
        {
            "name": "user"
        }
    ],
    "auth.create": [],
    "auth.store": [],
    "auth.edit": [
        {
            "name": "auth"
        }
    ],
    "auth.update": [
        {
            "name": "auth"
        }
    ],
    "auth.destroy": [
        {
            "name": "auth"
        }
    ],
    "invite.user": [],
    "register": [],
    "login": []
}
}
export {};
