<?php

namespace App\Models;

use Database\Factories\InvitationsFactory;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

/**
 * App\Models\Invitations
 *
 * @property int $id
 * @property int $company_id
 * @property int $number_of_invitations
 * @property array|null $registered
 * @property string $key
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static InvitationsFactory factory($count = null, $state = [])
 * @method static Builder|Invitations newModelQuery()
 * @method static Builder|Invitations newQuery()
 * @method static Builder|Invitations query()
 * @method static Builder|Invitations whereCompanyId($value)
 * @method static Builder|Invitations whereCreatedAt($value)
 * @method static Builder|Invitations whereId($value)
 * @method static Builder|Invitations whereKey($value)
 * @method static Builder|Invitations whereNumberOfInvitations($value)
 * @method static Builder|Invitations whereRegistered($value)
 * @method static Builder|Invitations whereUpdatedAt($value)
 * @mixin Eloquent
 */
class Invitations extends Model
{
    use HasFactory;

    protected $guarded = [];


    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($model){
            $model->key = Str::uuid()->toString();
        });
    }

    protected $casts = [
        'registered' => 'array'
    ];
}
